-- 코드를 입력하세요
SELECT y.CART_ID
FROM
(
    SELECT CART_ID FROM CART_PRODUCTS
    WHERE NAME = "Yogurt"
) y
INNER JOIN
(
    SELECT CART_ID FROM CART_PRODUCTS
    WHERE NAME = "Milk"
) m
ON y.CART_ID = m.CART_ID
ORDER BY CART_ID
;