# SELECT *
# FROM (
# SELECT USER_ID, PRODUCT_ID
# FROM ONLINE_SALE
#     ) a
# GROUP BY a.USER_ID, a.PRODUCT_ID
# HAVING a.
# ORDER BY a.USER_ID, a.PRODUCT_ID DESC;

SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) > 1
ORDER BY USER_ID, PRODUCT_ID DESC;