-- 코드를 입력하세요
SELECT     u.USER_ID,
    u.NICKNAME,
    CONCAT_WS(' ', u.CITY, u.STREET_ADDRESS1, IFNULL(u.STREET_ADDRESS2, '')) AS 전체주소,
    CONCAT(SUBSTR(u.TLNO, 1, 3), '-', SUBSTR(u.TLNO, 4, 4), '-', SUBSTR(u.TLNO, 8)) AS 전화번호
FROM USED_GOODS_BOARD b
    INNER JOIN USED_GOODS_USER u
    ON b.WRITER_ID = u.USER_ID
GROUP BY u.USER_ID
HAVING COUNT(u.USER_ID) >= 3
ORDER BY u.USER_ID DESC
;