-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, SUM(b.PRICE) as TOTAL_SALES
FROM (
    SELECT * 
    FROM USED_GOODS_BOARD 
    WHERE STATUS = "DONE"
      ) as b
    LEFT JOIN USED_GOODS_USER as u
    ON b.WRITER_ID = u.USER_ID
GROUP BY u.USER_ID
HAVING SUM(b.PRICE) >= 700000
ORDER BY SUM(b.PRICE)
;