-- 코드를 작성해주세요
SELECT DISTINCT(ID) AS ID, EMAIL, FIRST_NAME, LAST_NAME
FROM 
    DEVELOPERS D 
    JOIN 
    (
        SELECT NAME, CODE
        FROM SKILLCODES 
        WHERE NAME = 'Python' OR NAME = 'C#'
    ) S
    ON D.SKILL_CODE & S.CODE
ORDER BY ID
;