-- 코드를 작성해주세요
SELECT q2.YEAR, (q2.MAX_SIZE - q1.SIZE_OF_COLONY) as YEAR_DEV, q1.ID
FROM 
    ECOLI_DATA q1
    JOIN
    (
        SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) q2
    ON 
     YEAR(q1.DIFFERENTIATION_DATE) = q2.YEAR
ORDER BY YEAR, YEAR_DEV 
;