SELECT *
FROM (
    SELECT 
        CASE 
            WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = "Front End") 
                 AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = "Python") THEN 'A'
            WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = "C#") THEN 'B'
            WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = "Front End") THEN 'C'
            ELSE 'D'
        END AS GRADE, 
        ID, 
        EMAIL
    FROM DEVELOPERS
    ORDER BY GRADE, ID
    ) view1
WHERE view1.GRADE != 'D'
;
